version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  node-app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - '4000:4000'
    depends_on:
      - postgres
volumes:
  postgres: